// Static data + copy dictionary
const COPY = {
  es: {
    appName: 'OnCall Clinic',
    brand: 'Ibiza Care SL',
    step: 'Paso',
    of: 'de',
    // step 1
    s1_title: '¿Qué tipo de consulta necesitas?',
    s1_sub: 'Un médico colegiado te atenderá en tu ubicación.',
    s1_general: 'Consulta General',
    s1_general_sub: 'Síntomas comunes, revisiones, recetas.',
    s1_urgent: 'Urgencia No Vital',
    s1_urgent_sub: 'Atención prioritaria en menos de 20 min.',
    s1_ped: 'Pediatría',
    s1_ped_sub: 'Para niños de 0 a 14 años.',
    soon: 'PRÓXIMAMENTE',
    from: 'Desde',
    // step 2
    s2_title: 'Elige tu médico',
    s2_sub: 'Todos verificados por el Colegio de Médicos.',
    all: 'Todos',
    avail: 'Disponible ahora',
    top: 'Mejor valorados',
    near: 'Más cercanos',
    years: 'años',
    reviews: 'reseñas',
    eta: 'Llega en',
    select: 'Seleccionar',
    selected: 'Seleccionado',
    // step 3
    s3_title: 'Ubicación y síntomas',
    s3_loc: '¿Dónde te encuentras?',
    s3_loc_ph: 'Escribe tu dirección u hotel',
    s3_sym: 'Cuéntanos qué te pasa',
    s3_sym_ph: 'Describe tus síntomas, cuándo comenzaron, intensidad...',
    s3_quick: 'Síntomas frecuentes',
    fever: 'Fiebre',
    head: 'Dolor de cabeza',
    naus: 'Náuseas',
    abd: 'Dolor abdominal',
    allerg: 'Alergias',
    sum: 'Resumen',
    cont_type: 'Tipo de consulta',
    doctor: 'Médico',
    est_price: 'Precio estimado',
    // step 4
    s4_title: 'Confirma y paga',
    order: 'Tu pedido',
    consultation: 'Consulta',
    travel: 'Desplazamiento',
    included: 'incluido',
    total: 'Total',
    pay_method: 'Método de pago',
    card_num: 'Número de tarjeta',
    expiry: 'Exp.',
    cvc: 'CVC',
    ssl: 'Pago seguro SSL',
    stripe: 'Stripe Verified',
    accept: 'Acepto las',
    terms: 'condiciones de servicio',
    and: 'y la',
    privacy: 'política de privacidad',
    pay: 'Pagar',
    // buttons
    cont: 'Continuar',
    confirm: 'Confirmar y pagar',
    // success
    success_title: 'Pago confirmado',
    success_msg: 'Tu médico está en camino',
    success_eta: 'Llegada estimada',
    success_track: 'Seguir en tiempo real',
    success_call: 'Llamar al médico',
    success_msg_btn: 'Enviar mensaje',
    // misc
    lang_pills: ['ES', 'EN'],
  },
  en: {
    appName: 'OnCall Clinic',
    brand: 'Ibiza Care SL',
    step: 'Step',
    of: 'of',
    s1_title: 'What kind of visit do you need?',
    s1_sub: 'A licensed doctor will come to you.',
    s1_general: 'General Consultation',
    s1_general_sub: 'Common symptoms, check-ups, prescriptions.',
    s1_urgent: 'Non-Vital Urgent Care',
    s1_urgent_sub: 'Priority attention in under 20 min.',
    s1_ped: 'Pediatrics',
    s1_ped_sub: 'For children aged 0 to 14.',
    soon: 'COMING SOON',
    from: 'From',
    s2_title: 'Choose your doctor',
    s2_sub: 'All verified by the Medical Association.',
    all: 'All',
    avail: 'Available now',
    top: 'Top rated',
    near: 'Closest',
    years: 'yrs',
    reviews: 'reviews',
    eta: 'ETA',
    select: 'Select',
    selected: 'Selected',
    s3_title: 'Location & symptoms',
    s3_loc: 'Where are you?',
    s3_loc_ph: 'Type your address or hotel',
    s3_sym: 'Tell us what\u2019s going on',
    s3_sym_ph: 'Describe your symptoms, when they started, intensity...',
    s3_quick: 'Common symptoms',
    fever: 'Fever',
    head: 'Headache',
    naus: 'Nausea',
    abd: 'Abdominal pain',
    allerg: 'Allergies',
    sum: 'Summary',
    cont_type: 'Visit type',
    doctor: 'Doctor',
    est_price: 'Estimated price',
    s4_title: 'Confirm & pay',
    order: 'Your order',
    consultation: 'Consultation',
    travel: 'Travel fee',
    included: 'included',
    total: 'Total',
    pay_method: 'Payment method',
    card_num: 'Card number',
    expiry: 'Exp.',
    cvc: 'CVC',
    ssl: 'SSL secure payment',
    stripe: 'Stripe Verified',
    accept: 'I accept the',
    terms: 'terms of service',
    and: 'and the',
    privacy: 'privacy policy',
    pay: 'Pay',
    cont: 'Continue',
    confirm: 'Confirm & pay',
    success_title: 'Payment confirmed',
    success_msg: 'Your doctor is on the way',
    success_eta: 'Estimated arrival',
    success_track: 'Track in real time',
    success_call: 'Call the doctor',
    success_msg_btn: 'Send a message',
    lang_pills: ['ES', 'EN'],
  }
};

const CONSULT_TYPES = [
  { id: 'general', icon: 'stethoscope', price: 150, disabled: false },
  { id: 'urgent', icon: 'alert', price: 220, disabled: false, badge: 'urgent' },
  { id: 'ped', icon: 'baby', price: 180, disabled: true, badge: 'soon' },
];

const DOCTORS = [
  {
    id: 'd1',
    name: 'Dra. María García López',
    specialty_es: 'Medicina General',
    specialty_en: 'General Medicine',
    years: 12,
    rating: 4.9,
    reviews: 187,
    etaMin: 12,
    langs: ['ES', 'EN'],
    price: 150,
    verified: true,
    hue: 8,
    init: 'MG',
  },
  {
    id: 'd2',
    name: 'Dr. James Whitford',
    specialty_es: 'Medicina de Urgencias',
    specialty_en: 'Emergency Medicine',
    years: 15,
    rating: 4.8,
    reviews: 243,
    etaMin: 18,
    langs: ['EN', 'ES', 'FR'],
    price: 150,
    verified: true,
    hue: 220,
    init: 'JW',
  },
  {
    id: 'd3',
    name: 'Dra. Sofia Benedetti',
    specialty_es: 'Medicina General',
    specialty_en: 'General Medicine',
    years: 8,
    rating: 5.0,
    reviews: 94,
    etaMin: 22,
    langs: ['IT', 'ES', 'EN'],
    price: 150,
    verified: true,
    hue: 160,
    init: 'SB',
  },
];

Object.assign(window, { COPY, CONSULT_TYPES, DOCTORS });
